services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev_php
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: bash
    tty: true
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: dev
      DB_USERNAME: root
      DB_PASSWORD: root

  mysql:
    image: mysql:8
    container_name: dev_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql_data:
